export const ADMIN_ROUTE = '/'
export const LANDING_ROUTE = '/landing'
export const LOGIN_ROUTE = '/authorization'
export const REGISTRATION_ROUTE = '/registration'
export const USER_ROUTE = '/user'
export const GALLERY_ROUTE = '/gallery'
export const BASKET_ROUTE = '/shopbasket'